joint_limits:
  longitudinal_slide_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  transverse_slide_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  vertical_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0