joint_limits:
  assembly_robot_1_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  assembly_robot_1_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  assembly_robot_1_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  assembly_robot_1_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  assembly_robot_1_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  assembly_robot_1_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0